### PR TITLE
Adding new features: add library, upload file and change user password

### PR DESCRIPTION
**Pull request by pramadhana92**
- rename typo function from get_libaries to get_libraries
- add new command:
  1. add library
      argument: name and owner
      example: add library 'Joe Library' joe@example.com
  2. add file
      argument: filepath and library_id
      example: add file './joe photo.png' 1c17cddc-2864-407c-8fcf-6a325964d00b
  3. update password user
      argument: user_email and new_password
      example: update password joe@example.com foo1234
- update get_ajax function to support files as request argument
- update get_url function to support request with put function
- update Readme.md file with new feature

### CODE REVIEW

**Comment by HenriWahl** [comment]
Thanks @pramadhana92!

What an embarassing bug naming "get_libaries" 🤪... and thanks for the new functions!

**Comment by pramadhana92** [comment]
You're welcome!

I also wanna thanks to you to create this good wrapper. So I don't need to create one from zero.

By the way, in the readme.md there is  "This library is forked from [https://https://github.com/HenriWahl/seafadm](https://https//github.com/HenriWahl/seafadm)"

I put that word when I forked this library

**Comment by HenriWahl** [comment]
OK, I'll fix this as it is not forked from itself :-)
What was the highest version of Seafile you run it successfully with?

**Comment by pramadhana92** [comment]
i'm using seafile 6.3.4 CE.

The new function added is using web API v2.1 from the official web.

**Comment by HenriWahl** [comment]
Ah OK, thanks. I run it with 8.0.8 CE and works as well.

If you find the time - would you mind to update the README file with your new commands?

**Comment by pramadhana92** [comment]
I already did it

**Comment by HenriWahl** [comment]
Oh sorry, my bad. Now I found it :+1:

**Pull request merged**
